import Head from "next/head";
import Link from "next/link";

import { UserButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

export default function Home() {

  const {data} = api.post.getAll.useQuery()
  console.log(data)
  
  return (
    <>
      <header>
				<UserButton afterSignOutUrl="/"/>
			</header>
      <Head>
        <title>News-Shell</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
