import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

import Layout from "~/lib/layout/Layout"
import Header from "~/lib/layout/Header";
import Footer from "~/lib/layout/Footer";

export default function Home() {

  const {data} = api.post.getAll.useQuery()
  console.log(data)
  
  return (
    <>      
      <Head>
        <title>News-Shell</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Layout/>
      <Footer/>
    </>
  );
}
